### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eltociear**
fix link.

### CODE REVIEW

**Comment by Pwuts** [comment]
try learning markdown

**Comment by eltociear** [comment]
@Pwuts I'm sorry.
Here was the correct solution.

https://github.com/Significant-Gravitas/Auto-GPT-Plugins/pull/22

**Comment by Pwuts** [comment]
Sorry, I now see I was too quick to close your PR. I didn't see that the `<h1 center>` broke the markdown and that was fixed by your exit, so I interpreted it as a bogus edit (which we have been getting a lot of).

Thanks for submitting #22!

**Comment by eltociear** [comment]
@Pwuts No problem.
I also reconsidered the method of correction, and as a result, I was able to find a simpler way that still maintains the Markdown style, so I'm glad.

**Pull request closed without merging**
