### PR TITLE
Add Text Parser plugin

### PR DESCRIPTION
**Pull request by BBongKim**
**Background**
I saw [PR](https://github.com/Significant-Gravitas/Auto-GPT/pull/3031) on Auto-GPT Repo.
but, he seems busy. so I convert this code myself with small changes and added an EPUB parser.

### CODE REVIEW

**Review by pierluigi-failla — COMMENTED** [review]
I will suggest to add conditional `import` to your project (in both `parser_plugin.py` and `parsers.py`) because when the zip is created and added to AutoGPT you need to be sure that your deps are available in AutoGPT env. Something like:

```
try:
    import docx
    import ebooklib
    import json
    import yaml
    import markdown
    ...
except ImportError:
    print("The following deps need to be installed: ...")
```

**Comment by ntindle** [comment]
I really appreciate this, but I'd like this to be in the core of the project for some refactors that are coming up!

**Comment by BBongKim** [comment]
> I will suggest to add conditional `import` to your project (in both `parser_plugin.py` and `parsers.py`) because when the zip is created and added to AutoGPT you need to be sure that your deps are available in AutoGPT env. Something like:
> 
> ```
> try:
>     import docx
>     import ebooklib
>     import json
>     import yaml
>     import markdown
>     ...
> except ImportError:
>     print("The following deps need to be installed: ...")
> ```

thanks for your feedback!

**Comment by BBongKim** [comment]
> I really appreciate this, but I'd like this to be in the core of the project for some refactors that are coming up!

Alright, I agree with your idea and gonna find something I can do.

**Pull request closed without merging**
