### PR TITLE
Add an ISS position tracker to the Astro plugin

### PR DESCRIPTION
**Pull request by sr5434**
This change allows an AutoGPT agent to access the coordinates of the International Space Station.

### CODE REVIEW

**Review by ntindle — APPROVED** [review]

**Comment by sr5434** [comment]
When will this be merged?

**Comment by sr5434** [comment]
Is this still mergeable?

**Comment by sr5434** [comment]
@ntindle should I fix the conflicts

**Comment by ntindle** [comment]
@sr5434 yes

**Comment by sr5434** [comment]
Ok

**Comment by sr5434** [comment]
@ntindle I fixed the conflicts

**Comment by sr5434** [comment]
@ntindle the merge conflicts are fixed. Can this be merged?

**Pull request merged**
