### PR TITLE
Add comments to the source code for the Astro plugin

### PR DESCRIPTION
**Pull request by sr5434**
Add comments to the source code for the Astro plugin so it can more easily be understood.

### CODE REVIEW

**Review by ntindle — CHANGES_REQUESTED** [review]
python comments should go on the line above

**Comment by sr5434** [comment]
Is this better?

**Review by ntindle — APPROVED** [review]
Would love to see you add support for more of the functions of the api in the next pr!

**Comment by sr5434** [comment]
Yeah, I will probably add that next.

**Pull request merged**
