### PR TITLE
test plugin installation with every PR

### PR DESCRIPTION
**Pull request by h4ck3rk3y**

### CODE REVIEW

**Comment by ntindle** [comment]
If this doesn’t take too long to run, may be worth running every PR?

**Comment by h4ck3rk3y** [comment]
@ntindle this took me longer than I had expected but now 

1. It runs on every PR
2. Pulls the current zip from the current PR; if its on a fork on or the repository itself
3. Runs an installation of the plugin

Note, we run this against all plugins on this repository but perhaps running against simply `twitter` is enough as the `Zip` that its downloading is the same regardless of the plugin

Can edit this https://github.com/Significant-Gravitas/Auto-GPT-Plugins/pull/131/files#diff-a4191819a33cf0551ad8ed92b44df03c85a26b20f1fd09b8ae755740ce123572R22 to just `twitter` if we want to save some compute

**Comment by h4ck3rk3y** [comment]
@ntindle Sweet, will let it stay this way then.

I fixed the `autogpt-package` to make assertions on the installation of plugins being correct. Earlier we would install and put the installed terminal in the back; now we assert that the output is as expected.

**Comment by h4ck3rk3y** [comment]
The runtime of the test went up as I made some fixes; which makes us actually install the plugins dependencies properly

image


Here's an example ^ of the package running with AutoGPTTwitter. I have also renamed the plugins passable to the classes that AutoGPT expects. You can see that the plugin gets installed & runs fine.

Our package code asserts that the installation succeeds by asserting that the exit code is 0 for `python scripts/install_plugin_deps.py`

Let me know what you think @ntindle

**Review by ntindle — APPROVED** [review]

**Comment by ntindle** [comment]
This is great. We should notate the need for the plugin to be added to the workflow for first party plugins

**Pull request merged**
