### PR TITLE
Update README.md to add the Website-Carbon-Footprint Plugin.

### PR DESCRIPTION
**Pull request by arananet**
I've added my plugin into the list. 

Auto-GPT Website-Carbon-Footprint Plugin: Take advantage of the Website Carbon Footprint API with Auto-GPT. 

Glad to participate in this project.

### CODE REVIEW

**Comment by ntindle** [comment]
Can you move this to the lower table? The top one is for first-party plugins within this repo

**Review by ntindle — CHANGES_REQUESTED** [review]
Move to the correct table

**Comment by arananet** [comment]
Maybe I'm missing something.. but in my patch, i put the plugin into the second table (third party) because it's. Can you recheck please?

**Comment by arananet** [comment]
Any update @ntindle ? my plugin is on the correct table, as a third party one.

**Review by arananet — COMMENTED** [review]
Please accept the request so my plugin is available as third party. Thanks.

**Pull request merged**
